databases:
  - name: sendit_qaq4
    databaseName: sendit_qaq4
    user: sendit_qaq4_user

services:
  - type: web
    name: sendit_qaq4
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sendit_qaq4
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false